[toolchain]
channel = "stable"

[features]
seeds = false
skip-lint = false

[programs.devnet]
lydia_commodity_swap = "HsBV6Uhk4NV65zTK93ofoT8zYei91bezMdCFXgAPoKE8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ufukkarabag/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
