[toolchain]
channel = "stable"

[features]
seeds = false
skip-lint = false

[programs.localnet]
lydia_commodity_swap = "Ce7DZvMPxx62AaGCDbmHpQBsdsu5WpDmDiKDd5Qhi7v5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/ufukkarabag/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
